return {
PlaceObj('ModItemCode', {
	'name', "5.45x39 conversion",
	'comment', "converts the AK74 series rifles to proper caliber",
	'CodeFileName', "Code/5.45x39 conversion.lua",
}),
PlaceObj('ModItemCode', {
	'name', "5.56x45 Craft fix",
	'comment', "makes the basic ammo cheaper to craft, in line with all the other ammos",
	'CodeFileName', "Code/5.56x45 Craft fix.lua",
}),
PlaceObj('ModItemCode', {
	'name', "556 AMMO",
	'comment', "All 556 Ammo changes",
	'CodeFileName', "Code/556 AMMO.lua",
}),
PlaceObj('ModItemCode', {
	'name', "9mm AMMO",
	'comment', "All 9mm Ammo changes",
	'CodeFileName', "Code/9mm AMMO.lua",
}),
PlaceObj('ModItemCode', {
	'name', "7.62x54R conversion",
	'comment', "Converts SVD to 7.62x54R, 35DMG",
	'CodeFileName', "Code/7.62x54R conversion.lua",
}),
PlaceObj('ModItemCode', {
	'name', "762 WP Ammo",
	'comment', "All 762WP Ammo changes",
	'CodeFileName', "Code/762 WP Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "762Nato Ammo",
	'comment', "all 762 Nato ammo changes",
	'CodeFileName', "Code/762Nato Ammo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Caliber 5.45x39",
	'comment', "adds Caliber 5.45x39",
	'CodeFileName', "Code/Caliber 5.45x39.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Caliber 7.62x54R",
	'comment', "adds Caliber 7.62x54R",
	'CodeFileName', "Code/Caliber 7.62x54R.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Deagle Changes",
	'comment', "Deagle range up to 20, pen removed",
	'CodeFileName', "Code/Deagle Changes.lua",
}),
PlaceObj('ModItemCode', {
	'name', "LootDef 545x39",
	'comment', "inserts the new caliber into loot drops",
	'CodeFileName', "Code/LootDef 545x39.lua",
}),
PlaceObj('ModItemCode', {
	'name', "LootDef Adonis Flanker",
	'comment', "gives the right ammo to this npc 545x39",
	'CodeFileName', "Code/LootDef Adonis Flanker.lua",
}),
PlaceObj('ModItemCode', {
	'name', "LootDef Chimurenga",
	'comment', "chimichanga 545x39",
	'CodeFileName', "Code/LootDef Chimurenga.lua",
}),
PlaceObj('ModItemCode', {
	'name', "LootDef ThugGunner",
	'comment', "ThugGunner 5.45x39",
	'CodeFileName', "Code/LootDef ThugGunner.lua",
}),
PlaceObj('ModItemCode', {
	'name', "LootDefLegionScout_Stronger_Elite",
	'comment', "gives the right ammo to this npc 545x39",
	'CodeFileName', "Code/LootDefLegionScout_Stronger_Elite.lua",
}),
PlaceObj('ModItemCode', {
	'comment', "Bereta unchanged",
	'CodeFileName', "Code/Script.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script10",
	'comment', "ak74, dmg 22, range 35, no pen",
	'CodeFileName', "Code/Script10.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script11",
	'comment', "AKSU dmg 21, range 30, should have this lower AP?",
	'CodeFileName', "Code/Script11.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script12",
	'comment', "m16a2 dmg 19, range 30, no pen",
	'CodeFileName', "Code/Script12.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script122",
	'comment', "mg42 dmg 26, range 45, no pen",
	'CodeFileName', "Code/Script122.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script123",
	'comment', "PSG1 dmg 26, range 60, no pen, aim 8, crit30",
	'CodeFileName', "Code/Script123.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script124",
	'comment', "FNMinimi 19dmg, range 45, aim 6",
	'CodeFileName', "Code/Script124.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script125",
	'comment', "W1894 dmg 27, range 30, crit 50, aim 7",
	'CodeFileName', "Code/Script125.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script126",
	'comment', "M24 26dmg, range 50, aim 10, crit0/30",
	'CodeFileName', "Code/Script126.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script127",
	'comment', "m14 dmg 26, range 30, no pen, aim 6",
	'CodeFileName', "Code/Script127.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script128",
	'comment', "BrowningHP dmg 15, range 17",
	'CodeFileName', "Code/Script128.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script1282",
	'comment', "G36 dmg 19, aim 8, range 30, no pen",
	'CodeFileName', "Code/Script1282.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script12822",
	'comment', "FNFAL dmg 26, range 30, no pen",
	'CodeFileName', "Code/Script12822.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script128222",
	'comment', "G36 dmg 19, aim 8, range 30, no pen",
	'CodeFileName', "Code/Script128222.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script13",
	'comment', "RPk, damage 24, range 45",
	'CodeFileName', "Code/Script13.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script14",
	'comment', "ar15 dmg 19, range 30, no pen",
	'CodeFileName', "Code/Script14.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script15",
	'comment', "AUG dmg 19, range 30, no pen",
	'CodeFileName', "Code/Script15.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script16",
	'comment', "barret range 60",
	'CodeFileName', "Code/Script16.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script17",
	'comment', "moved to caliber conversion, SVD",
	'CodeFileName', "Code/Script17.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script18",
	'comment', "gewehr no pen, 26dmg, critchancescaled 30",
	'CodeFileName', "Code/Script18.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script19",
	'comment', "famas dmg 18, range 30, no pen",
	'CodeFileName', "Code/Script19.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script2",
	'comment', "UZI rebalance, damage to 15, range to 20",
	'CodeFileName', "Code/Script2.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script20",
	'comment', "Galil dmg 26, range 30, no pen",
	'CodeFileName', "Code/Script20.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script21",
	'comment', "HK21 dmg 26, range 45, no pen",
	'CodeFileName', "Code/Script21.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script22",
	'comment', "m4commando dmg 19, range 30, no pen",
	'CodeFileName', "Code/Script22.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Sunmaker_ArmoredBleeding",
	'comment', "makes a status effect that applies bleed if an enemy's armor is pierced.",
	'CodeFileName', "Code/Sunmaker_ArmoredBleeding.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script235",
	'comment', "unused",
	'CodeFileName', "Code/Script235.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script24",
	'comment', "for tex's revolvers",
	'CodeFileName', "Code/Script24.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script3",
	'comment', "Peacemaker dmg 20",
	'CodeFileName', "Code/Script3.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script4",
	'comment', "Anaconda dmg 22, no more pen",
	'CodeFileName', "Code/Script4.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script5",
	'comment', "Glock18 range 15",
	'CodeFileName', "Code/Script5.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script6",
	'comment', "mp5k damage to 15, range 20",
	'CodeFileName', "Code/Script6.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script7",
	'comment', "MP5 damage to 15, range 20",
	'CodeFileName', "Code/Script7.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script8",
	'comment', "mp40, reliability 70, dmg 16, range 20",
	'CodeFileName', "Code/Script8.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script9",
	'comment', "ak47 dmg 24, range 30, no pen",
	'CodeFileName', "Code/Script9.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Sunmaker_5.45x39 Craftable",
	'comment', "adds the recipes to make them craftable via sec. ops.",
	'CodeFileName', "Code/Sunmaker_5.45x39 Craftable.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Sunmaker_762x54R Craftable",
	'comment', "adds the recipes to make them craftable via sec. ops.",
	'CodeFileName', "Code/Sunmaker_762x54R Craftable.lua",
}),
PlaceObj('ModItemCode', {
	'name', "WeaponModFlashlight",
	'comment', "gives flashlights bonus acc at 1st aim level, 1/2 of vert grip",
	'CodeFileName', "Code/WeaponModFlashlight.lua",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_545x39_Basic",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/545x39/545X39_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(973776974354, --[[ModItemInventoryItemCompositeDef _545x39_Basic DisplayName]] "5.45x39 Standard Bullet"),
	'DisplayNamePlural', T(775344723155, --[[ModItemInventoryItemCompositeDef _545x39_Basic DisplayNamePlural]] "5.45x39 Standard Bullets"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(773433779815, --[[ModItemInventoryItemCompositeDef _545x39_Basic Description]] "5.45x39 Ammo for Soviet Assault Rifles."),
	'MaxStacks', 500,
	'Caliber', "545x39",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_545x39_AP",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/545x39/545X39_bullets_armor_piercing.png",
	'ItemType', "",
	'DisplayName', T(683787187344, --[[ModItemInventoryItemCompositeDef _545x39_AP DisplayName]] "5.45x39 Armor Piercing Bullet"),
	'DisplayNamePlural', T(732973898203, --[[ModItemInventoryItemCompositeDef _545x39_AP DisplayNamePlural]] "5.45x39 Armor Piercing Bullets"),
	'colorStyle', "AmmoAPColor",
	'Description', T(763876870528, --[[ModItemInventoryItemCompositeDef _545x39_AP Description]] "5.45x39 Ammo for Soviet Assault Rifles."),
	'MaxStacks', 500,
	'Caliber', "545x39",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_545x39_HP",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/545x39/545X39_bullets_hollow_point.png",
	'ItemType', "",
	'DisplayName', T(513984173710, --[[ModItemInventoryItemCompositeDef _545x39_HP DisplayName]] "5.45x39 Hollow Point Bullet"),
	'DisplayNamePlural', T(712564132220, --[[ModItemInventoryItemCompositeDef _545x39_HP DisplayNamePlural]] "5.45x39 Hollow Point Bullets"),
	'colorStyle', "AmmoHPColor",
	'Description', T(986970429666, --[[ModItemInventoryItemCompositeDef _545x39_HP Description]] "5.45x39 Ammo for Soviet Assault Rifles."),
	'MaxStacks', 500,
	'Caliber', "545x39",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_545x39_Match",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/545x39/545X39_bullets_match.png",
	'ItemType', "",
	'DisplayName', T(633486712212, --[[ModItemInventoryItemCompositeDef _545x39_Match DisplayName]] "5.45x39 Match Bullet"),
	'DisplayNamePlural', T(722551283237, --[[ModItemInventoryItemCompositeDef _545x39_Match DisplayNamePlural]] "5.45x39 Match Bullets"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(709912465567, --[[ModItemInventoryItemCompositeDef _545x39_Match Description]] "5.45x39 Ammo for Soviet Assault Rifles."),
	'AdditionalHint', "",
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_545x39_Tracer",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/545x39/545X39_bullets_tracer.png",
	'ItemType', "",
	'DisplayName', T(691878650506, --[[ModItemInventoryItemCompositeDef _545x39_Tracer DisplayName]] "5.45x39 Tracer Bullet"),
	'DisplayNamePlural', T(508055921325, --[[ModItemInventoryItemCompositeDef _545x39_Tracer DisplayNamePlural]] "5.45x39 Tracer Bullets"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(897571371095, --[[ModItemInventoryItemCompositeDef _545x39_Tracer Description]] "5.45x39 Ammo for Soviet Assault Rifles."),
	'MaxStacks', 500,
	'Caliber', "545x39",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762x54R_Basic",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/762X54R_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(888542979224, --[[ModItemInventoryItemCompositeDef _762x54R_Basic DisplayName]] "7.62x54R Standard Bullet"),
	'DisplayNamePlural', T(827393123590, --[[ModItemInventoryItemCompositeDef _762x54R_Basic DisplayNamePlural]] "7.62x54R Standard Bullets"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(465368075351, --[[ModItemInventoryItemCompositeDef _762x54R_Basic Description]] "7.62x54R Warsaw Pact ammo for Rifles and Sniper Rifles."),
	'MaxStacks', 500,
	'Caliber', "762x54R",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762x54R_AP",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/762X54R_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(446139469813, --[[ModItemInventoryItemCompositeDef _762x54R_AP DisplayName]] "7.62x54R Armor Piercing Bullet"),
	'DisplayNamePlural', T(380560376761, --[[ModItemInventoryItemCompositeDef _762x54R_AP DisplayNamePlural]] "7.62x54R Armor Piercing Bullets"),
	'colorStyle', "AmmoAPColor",
	'Description', T(182774355927, --[[ModItemInventoryItemCompositeDef _762x54R_AP Description]] "7.62x54R Warsaw Pact ammo for Rifles and Sniper Rifles."),
	'MaxStacks', 500,
	'Caliber', "762x54R",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762x54R_HP",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/762X54R_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(135944473536, --[[ModItemInventoryItemCompositeDef _762x54R_HP DisplayName]] "7.62x54R Hollow Point Bullet"),
	'DisplayNamePlural', T(915514719402, --[[ModItemInventoryItemCompositeDef _762x54R_HP DisplayNamePlural]] "7.62x54R Hollow Point Bullets"),
	'colorStyle', "AmmoHPColor",
	'Description', T(674259739390, --[[ModItemInventoryItemCompositeDef _762x54R_HP Description]] "7.62x54R Warsaw Pact ammo for Rifles and Sniper Rifles."),
	'MaxStacks', 500,
	'Caliber', "762x54R",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762x54R_Match",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/762X54R_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(626761810719, --[[ModItemInventoryItemCompositeDef _762x54R_Match DisplayName]] "7.62x54R Match Bullet"),
	'DisplayNamePlural', T(392143811556, --[[ModItemInventoryItemCompositeDef _762x54R_Match DisplayNamePlural]] "7.62x54R Match Bullets"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(960791707110, --[[ModItemInventoryItemCompositeDef _762x54R_Match Description]] "7.62x54R Warsaw Pact ammo for Rifles and Sniper Rifles."),
	'MaxStacks', 500,
	'Caliber', "762x54R",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762x54R_Tracer",
	'object_class', "Ammo",
	'Repairable', false,
	'Icon', "Mod/mXGyLTd/icons/ammo/762X54R_bullets_basic.png",
	'ItemType', "",
	'DisplayName', T(320648047495, --[[ModItemInventoryItemCompositeDef _762x54R_Tracer DisplayName]] "7.62x54R Tracer Bullet"),
	'DisplayNamePlural', T(680114527743, --[[ModItemInventoryItemCompositeDef _762x54R_Tracer DisplayNamePlural]] "7.62x54R Tracer Bullets"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(994328929958, --[[ModItemInventoryItemCompositeDef _762x54R_Tracer Description]] "7.62x54R Warsaw Pact ammo for Rifles and Sniper Rifles."),
	'MaxStacks', 500,
	'Caliber', "762x54R",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "556test",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/556_nato_bullets_armor_piercing",
	'DisplayName', T(623285288766, --[[ModItemInventoryItemCompositeDef 556test DisplayName]] "5.56 mm Armor Piercing"),
	'DisplayNamePlural', T(269460472699, --[[ModItemInventoryItemCompositeDef 556test DisplayNamePlural]] "5.56 mm Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(354788703494, --[[ModItemInventoryItemCompositeDef 556test Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(348456911043, --[[ModItemInventoryItemCompositeDef 556test AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
}),
PlaceObj('ModItemLootDef', {
	Comment = "enemy rebels",
	comment = "npc that uses SVD, giving them chance to drop SVD ammo",
	group = "Enemy - Rebels",
	id = "RebelSniper",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		Condition = 89,
		RandomizeCondition = true,
		item = "DragunovSVD",
		stack_max = 1,
		stack_min = 1,
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_Varied",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "RebelsArmor_Pants_Chest_Light_Randomized",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "EnemyValuables",
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "enemy thugs",
	comment = "npc that uses SVD, giving them chance to drop SVD ammo",
	group = "Enemy - Thugs",
	id = "ThugSniper_Stronger",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		Condition = 87,
		RandomizeCondition = true,
		drop_chance_mod = 0,
		item = "Knife",
		stack_max = 1,
		stack_min = 1,
	}),
	PlaceObj('LootEntryInventoryItem', {
		Condition = 61,
		RandomizeCondition = true,
		item = "DragunovSVD",
		stack_max = 1,
		stack_min = 1,
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "ThugsArmor_Pants_Chest_Light",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_Varied",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "EnemyValuables",
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_Basic",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		item = "_762x54R_Basic",
		stack_max = 90,
		stack_min = 30,
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_AP",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		item = "_762x54R_AP",
		stack_max = 90,
		stack_min = 30,
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_HP",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		item = "_762x54R_HP",
		stack_max = 90,
		stack_min = 30,
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_Match",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		item = "_762x54R_Match",
		stack_max = 90,
		stack_min = 30,
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_Tracer",
	loot = "all",
	PlaceObj('LootEntryInventoryItem', {
		item = "_762x54R_Tracer",
		stack_max = 90,
		stack_min = 30,
	}),
}),
PlaceObj('ModItemLootDef', {
	Comment = "list",
	id = "Sunmaker-Loot-76254R_Varied",
	loot = "all",
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_AP",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_Basic",
		weight = 10000,
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_HP",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_Match",
	}),
	PlaceObj('LootEntryLootDef', {
		loot_def = "Sunmaker-Loot-76254R_Tracer",
	}),
}),
}
