return PlaceObj('ModDef', {
	'title', "New Calibers and Weapon Rebalance",
	'description', "Weapons rebalanced, new caliber(s)\nwhat's new:\n7.62x54R\n5.45x39\nall ammo causes bleeding unless you are armored (ammo pen < armor level)\n\nwhat's next, 22lr for annoying the legion?\n\nEach firearm using the same caliber should share the same damage, +/- 1-2 where I think a longer barrel would apply greater velocity etc.\n\nMost firearms changed except for some quest weapons.\nInterestingly, the base game gives the guns their armor penetration. This mod removes this from the guns.\n\nFor those of you who want to edit this mod, subscribe to the mod enabler/editor and use that to tinker with what I've made. \n\nI'm not entirely sure what the devs wanted \"range\" to be, is it the effective distance of the caliber or the range at which it's easy to line-up a shot?\n\nI'm still working on balance, the snipers might feel gutted especially if that's your preferred playstyle. Maybe adding crit on headshots and increasing aim bonuses on snipers might balance it out.\n\nI'm thinking about stabilizing damage across the board and just finding a way to make snipers useful without making them the be-all end-all when it comes to firefights. Should I just JA 1.13 it?",
	'image', "Mod/mXGyLTd/pic.png",
	'last_changes', '1. 5.56x45mm ammo now needs 10 parts instead of 30 to make in sector ops. This is in-line with all the other calibers.\n2. ALL AMMO CAUSES BLEEDING, GET THAT PATCHED UP.\n\nWorking on:\n1. Icons for 7.62x54R\n2. More "sensible" weapon mod changes.\n3. HP ammo to cause 2 stack bleeding WIP.',
	'id', "mXGyLTd",
	'content_path', "Mod/mXGyLTd/",
	'author', "Sunmaker - ban riki 24/7",
	'version_major', 1,
	'version_minor', 8,
	'version', 196,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/5.45x39 conversion.lua",
		"Code/5.56x45 Craft fix.lua",
		"Code/556 AMMO.lua",
		"Code/9mm AMMO.lua",
		"Code/7.62x54R conversion.lua",
		"Code/762 WP Ammo.lua",
		"Code/762Nato Ammo.lua",
		"Code/Caliber 5.45x39.lua",
		"Code/Caliber 7.62x54R.lua",
		"Code/Deagle Changes.lua",
		"Code/LootDef 545x39.lua",
		"Code/LootDef Adonis Flanker.lua",
		"Code/LootDef Chimurenga.lua",
		"Code/LootDef ThugGunner.lua",
		"Code/LootDefLegionScout_Stronger_Elite.lua",
		"Code/Script.lua",
		"Code/Script10.lua",
		"Code/Script11.lua",
		"Code/Script12.lua",
		"Code/Script122.lua",
		"Code/Script123.lua",
		"Code/Script124.lua",
		"Code/Script125.lua",
		"Code/Script126.lua",
		"Code/Script127.lua",
		"Code/Script128.lua",
		"Code/Script1282.lua",
		"Code/Script12822.lua",
		"Code/Script128222.lua",
		"Code/Script13.lua",
		"Code/Script14.lua",
		"Code/Script15.lua",
		"Code/Script16.lua",
		"Code/Script17.lua",
		"Code/Script18.lua",
		"Code/Script19.lua",
		"Code/Script2.lua",
		"Code/Script20.lua",
		"Code/Script21.lua",
		"Code/Script22.lua",
		"Code/Sunmaker_ArmoredBleeding.lua",
		"Code/Script235.lua",
		"Code/Script24.lua",
		"Code/Script3.lua",
		"Code/Script4.lua",
		"Code/Script5.lua",
		"Code/Script6.lua",
		"Code/Script7.lua",
		"Code/Script8.lua",
		"Code/Script9.lua",
		"Code/Sunmaker_5.45x39 Craftable.lua",
		"Code/Sunmaker_762x54R Craftable.lua",
		"Code/WeaponModFlashlight.lua",
		"InventoryItem/_545x39_Basic.lua",
		"InventoryItem/_545x39_AP.lua",
		"InventoryItem/_545x39_HP.lua",
		"InventoryItem/_545x39_Match.lua",
		"InventoryItem/_545x39_Tracer.lua",
		"InventoryItem/_762x54R_Basic.lua",
		"InventoryItem/_762x54R_AP.lua",
		"InventoryItem/_762x54R_HP.lua",
		"InventoryItem/_762x54R_Match.lua",
		"InventoryItem/_762x54R_Tracer.lua",
		"InventoryItem/556test.lua",
	},
	'saved', 1690136057,
	'code_hash', -4998690617086801283,
	'steam_id', "3007837871",
})