-- ========== GENERATED BY CraftOperationsRecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_556_Basic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "556_Basic",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_545x39_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_545x39_AP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_545x39_AP_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_545x39_Basic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_545x39_Basic_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_545x39_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_545x39_HP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_545x39_HP_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_545x39_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_545x39_Match",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_545x39_Match_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_545x39_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_545x39_Tracer",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_545x39_Tracer_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762x54R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762x54R_AP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_762x54R_AP_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762x54R_Basic",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_762x54R_Basic_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762x54R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762x54R_HP",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_762x54R_HP_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762x54R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762x54R_Match",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_762x54R_Match_Craft",
	save_in = "Libs/Network",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 15,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
		PlaceObj('RecipeIngredient', {
			'item', "_762x54R_Basic",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_762x54R_Tracer",
		'amount', 30,
	}),
	group = "Ammo",
	id = "Sunmaker_762x54R_Tracer_Craft",
	save_in = "Libs/Network",
})

